import{a as M,i as n,S as P}from"./assets/vendor-CpJWJOGi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();let B="49718296-934511357bd75d639d0773032",$="https://pixabay.com/api/";async function T(i,t,o){try{return o=o>=15?o:15,(await M.get($,{params:{key:B,q:i,page:t,per_page:o,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch(a){throw n.error({title:"Ошибка",message:"Не удалось загрузить изображения."}),a}}let u=document.querySelector("ul.gallery"),p=document.querySelector("#load-more-btn"),w=document.querySelector("#loader"),L=document.querySelector("#loaderText"),m=new P(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});function C(i,t=!1){if(i.length===0){t||(u.innerHTML="",m.refresh());let a={theme:"dark",position:"topRight",maxWidth:432,backgroundColor:"#EF4040",icon:"fa-solid fa-triangle-exclamation",message:"Sorry, there are no images matching your search query. Please try again!"};n.show(a);return}let o=i.map(function(a){let{webformatURL:e,largeImageURL:r,tags:l,likes:S,views:q,comments:x,downloads:E}=a;return`
        <li class="gallery-item">
          <a href="${r}" class="gallery-link">
            <img
              class="gallery-image"
              src="${e}"
              alt="${l}"
            />
            <div class="image-description">
              <div><h2>Likes</h2><p>${S}</p></div>
              <div><h2>Views</h2><p>${q}</p></div>
              <div><h2>Comments</h2><p>${x}</p></div>
              <div><h2>Downloads</h2><p>${E}</p></div>
            </div>
          </a>
        </li>
      `}).join("");t?u.insertAdjacentHTML("beforeend",o):u.innerHTML=o,m.refresh()}function H(){u.innerHTML="",m.refresh()}function v(){L.textContent="Loading images, please wait...",w.classList.remove("hidden")}function f(){L.textContent="",w.classList.add("hidden")}function O(){p.classList.remove("hidden")}function s(){p.classList.add("hidden")}const g=document.querySelector("form"),R=document.querySelector("#load-more-btn"),c={theme:"dark",position:"topRight",maxWidth:432,backgroundColor:"#EF4040",icon:"fa-solid fa-triangle-exclamation"};let h="",d=1;const y=15;s();f();async function b(i=!1){const t=await T(h,d,y),o=t.hits;if(o.length===0){s(),n.show({...c,message:"No image available."});return}if(C(o),i){const a=document.querySelector(".gallery-item");if(a){const e=a.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}d*y>=t.totalHits?(s(),n.show({...c,message:"We're sorry, but you've reached the end of search results."})):O()}g.addEventListener("submit",async i=>{i.preventDefault();const t=g.querySelector("input");if(h=t.value.trim(),!h){n.show({...c,message:"Enter search param"});return}d=1,H(),s(),v();try{await b()}catch(o){s(),n.show({...c,message:"Something went wrong. Please try again!"}),console.error(o)}finally{f()}t.value=""});R.addEventListener("click",async()=>{d+=1,s(),v();try{await b(!0)}catch(i){d-=1,n.show({...c,message:"Something went wrong. Please try again!"}),console.error(i)}finally{f()}});
//# sourceMappingURL=index.js.map
