import{a as E,i as n,S as x}from"./assets/vendor-CpJWJOGi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();let P="49718296-934511357bd75d639d0773032",M="https://pixabay.com/api/";async function B(a,t,r){try{return(await E.get(M,{params:{key:P,q:a,page:t,per_page:r,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch(i){throw n.error({title:"Ошибка",message:"Не удалось загрузить изображения."}),i}}let f=document.querySelector("ul.gallery"),p=document.querySelector("#load-more-btn"),y=document.querySelector("#loader"),w=document.querySelector("#loaderText"),$=new x(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});function T(a){if(a.length===0){let r={theme:"dark",position:"topRight",maxWidth:432,backgroundColor:"#EF4040",icon:"fa-solid fa-triangle-exclamation",message:"Sorry, there are no images matching your search query. Please try again!"};n.show(r);return}let t=a.map(function(r){let{webformatURL:i,largeImageURL:e,tags:o,likes:l,views:b,comments:S,downloads:q}=r;return`<li class="gallery-item">
      <a href="${e}" class="gallery-link">
        <img
            class="gallery-image"
            src="${i}" 
            alt="${o}"
        />
        <div class="image-description">
          <div><h2>Likes</h2><p>${l}</p></div>
          <div><h2>Views</h2><p>${b}</p></div>
          <div><h2>Comments</h2><p>${S}</p></div>
          <div><h2>Downloads</h2><p>${q}</p></div>
        </div>
      </a>
      </li>
    `});f.innerHTML+=t.join(""),$.refresh()}function H(){f.innerHTML=""}function L(){w.innerHTML="Loading images, please wait...",y.classList.add("loader")}function m(){w.innerHTML=null,y.classList.remove("loader")}function O(){p.style.display="block"}function s(){p.style.display="none"}const g=document.querySelector("form"),R=document.querySelector("#load-more-btn"),c={theme:"dark",position:"topRight",maxWidth:432,backgroundColor:"#EF4040",icon:"fa-solid fa-triangle-exclamation"};let u="",d=1;const h=15;s();m();function v(a=!1){return B(u,d,h).then(t=>{const r=t.hits;if(r.length===0){s(),n.show({...c,message:"No image available."});return}if(T(r),a){const i=document.querySelector(".gallery-item");if(i){const e=i.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}d*h>=t.totalHits?(s(),n.show({...c,message:"We're sorry, but you've reached the end of search results."})):O()})}g.addEventListener("submit",a=>{a.preventDefault();const t=g.querySelector("input");if(u=t.value.trim(),!u){n.show({...c,message:"Enter search param"});return}d=1,H(),s(),L(),v().catch(r=>{s(),n.show({...c,message:"Something went wrong. Please try again!"}),console.error(r)}).finally(()=>{m()}),t.value=""});R.addEventListener("click",()=>{d+=1,s(),L(),v(!0).catch(a=>{d-=1,n.show({...c,message:"Something went wrong. Please try again!"}),console.error(a)}).finally(()=>{m()})});
//# sourceMappingURL=index.js.map
