import{a as E,i as n,S as x}from"./assets/vendor-CpJWJOGi.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();let P="49718296-934511357bd75d639d0773032",M="https://pixabay.com/api/";async function B(a,o,t){try{return t=t>=15?t:15,(await E.get(M,{params:{key:P,q:a,page:o,per_page:t,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch(i){throw n.error({title:"Ошибка",message:"Не удалось загрузить изображения."}),i}}let f=document.querySelector("ul.gallery"),y=document.querySelector("#load-more-btn"),p=document.querySelector("#loader"),w=document.querySelector("#loaderText"),$=new x(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});function T(a){if(a.length===0){let t={theme:"dark",position:"topRight",maxWidth:432,backgroundColor:"#EF4040",icon:"fa-solid fa-triangle-exclamation",message:"Sorry, there are no images matching your search query. Please try again!"};n.show(t);return}let o=a.map(function(t){let{webformatURL:i,largeImageURL:e,tags:r,likes:l,views:b,comments:S,downloads:q}=t;return`<li class="gallery-item">
      <a href="${e}" class="gallery-link">
        <img
            class="gallery-image"
            src="${i}" 
            alt="${r}"
        />
        <div class="image-description">
          <div><h2>Likes</h2><p>${l}</p></div>
          <div><h2>Views</h2><p>${b}</p></div>
          <div><h2>Comments</h2><p>${S}</p></div>
          <div><h2>Downloads</h2><p>${q}</p></div>
        </div>
      </a>
      </li>
    `});f.innerHTML+=o.join(""),$.refresh()}function H(){f.innerHTML=""}function L(){w.innerHTML="Loading images, please wait...",p.classList.add("loader")}function m(){w.innerHTML=null,p.classList.remove("loader")}function O(){y.style.display="block"}function s(){y.style.display="none"}const h=document.querySelector("form"),R=document.querySelector("#load-more-btn"),c={theme:"dark",position:"topRight",maxWidth:432,backgroundColor:"#EF4040",icon:"fa-solid fa-triangle-exclamation"};let u="",d=1;const g=15;s();m();function v(a=!1){return B(u,d,g).then(o=>{const t=o.hits;if(t.length===0){s(),n.show({...c,message:"No image available."});return}if(T(t),a){const i=document.querySelector(".gallery-item");if(i){const e=i.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}d*g>=o.totalHits?(s(),n.show({...c,message:"We're sorry, but you've reached the end of search results."})):O()})}h.addEventListener("submit",a=>{a.preventDefault();const o=h.querySelector("input");if(u=o.value.trim(),!u){n.show({...c,message:"Enter search param"});return}d=1,H(),s(),L(),v().catch(t=>{s(),n.show({...c,message:"Something went wrong. Please try again!"}),console.error(t)}).finally(()=>{m()}),o.value=""});R.addEventListener("click",()=>{d+=1,s(),L(),v(!0).catch(a=>{d-=1,n.show({...c,message:"Something went wrong. Please try again!"}),console.error(a)}).finally(()=>{m()})});
//# sourceMappingURL=index.js.map
